markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 微笑的世界
host: wmz.hgzp.com

meta:
    author:
        name:  smilebaby
        email: smilebaby@example.com
        disqus: wmz              # Disqus缩略标识
        gcse: 001731541720927913316:ihk9vkckjec     # Google自定义搜索标识ID
        github: weimingzhen                         # GitHub账号
        gravatar: 1c88e9f8a4c605fd6bd8bb868ac94209  # Gravatar头像标识



    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

custom:
    category:
        life:  生活
        study: 学习
        work:  工作
        link:  收藏
        test:  测试
    categories:
      - name:  life
        title: 生活

      - name:  study
        title: 学习

      - name:  work
        title: 工作

      - name:  link
        title: 收藏  

      - name:  test
        title: 测试  
